import { MarketplaceItem } from './marketplace-types';

export const SEED_MARKETPLACE_ITEMS: MarketplaceItem[] = [
    {
        id: 'seed-atomic',
        title: 'Atomic Chess',
        description: 'Captured pieces explode! A chaotic variant where captures destroy all surrounding non-pawn pieces.',
        type: 'game',
        imageUrl: '/variants/atomic.jpg',
        creator_handle: '@chessperiment',
        stars_total: 45,
        stars_count: 10,
        views: 1200,
        forkCount: 0,
        isNew: false,
        date_published: new Date('2024-01-01'),
        rating: 4.5,
        reviewCount: 3,
    },
    {
        id: 'seed-960',
        title: 'Chess960 (Fischer Random)',
        description: 'The classic randomized starting position variant. 960 possible setups to test your opening creativity.',
        type: 'game',
        imageUrl: '/variants/chess960.jpg',
        creator_handle: '@chessperiment',
        stars_total: 48,
        stars_count: 12,
        views: 2500,
        forkCount: 0,
        isNew: false,
        date_published: new Date('2024-01-05'),
        rating: 4.0,
        reviewCount: 5,
    },
    {
        id: 'seed-koth',
        title: 'King of the Hill',
        description: 'Control the center! Win by moving your King to one of the four central squares (d4, e4, d5, e5).',
        type: 'game',
        imageUrl: '/variants/koth.jpg',
        creator_handle: '@chessperiment',
        stars_total: 38,
        stars_count: 8,
        views: 850,
        forkCount: 0,
        isNew: true,
        date_published: new Date('2024-03-10'),
        rating: 4.8,
        reviewCount: 2,
    },
    {
        id: 'seed-horde',
        title: 'Horde Chess',
        description: 'Can you survive the swarm? White has a standard army, while Black has 36 pawns ready to overwhelm.',
        type: 'game',
        imageUrl: '/variants/horde.jpg',
        creator_handle: '@chessperiment',
        stars_total: 42,
        stars_count: 10,
        views: 1500,
        forkCount: 0,
        isNew: false,
        date_published: new Date('2024-02-15'),
        rating: 4.2,
        reviewCount: 4,
    },
    {
        id: 'seed-extinction',
        title: 'Extinction Chess',
        description: 'Lose a species, lose the game! The goal is to eliminate all pieces of any one type (e.g., all Knights).',
        type: 'game',
        imageUrl: '/variants/extinction.jpg',
        creator_handle: '@chessperiment',
        stars_total: 35,
        stars_count: 7,
        views: 600,
        forkCount: 0,
        isNew: true,
        date_published: new Date('2024-03-12'),
        rating: 5.0,
        reviewCount: 1,
    },
    {
        id: 'seed-neon-board',
        title: 'Neon Glow Board',
        description: 'A vibrant neon-themed board with glowing grid lines and dark background. Perfect for late-night sessions.',
        type: 'board',
        imageUrl: '',
        creator_handle: '@neonmaker',
        stars_total: 20,
        stars_count: 5,
        views: 320,
        forkCount: 2,
        isNew: true,
        date_published: new Date('2024-03-18'),
        rating: 4.0,
        reviewCount: 2,
    },
    {
        id: 'seed-pixel-pieces',
        title: 'Retro Pixel Pieces',
        description: '8-bit inspired pixel art piece set. Nostalgic vibes for your chess games.',
        type: 'pieces',
        imageUrl: '',
        creator_handle: '@pixelartist',
        stars_total: 28,
        stars_count: 6,
        views: 410,
        forkCount: 5,
        isNew: false,
        date_published: new Date('2024-02-20'),
        rating: 4.7,
        reviewCount: 3,
    },
    {
        id: 'seed-marble-board',
        title: 'Italian Marble Board',
        description: 'Elegant marble-textured board inspired by classical Italian chess tables.',
        type: 'board',
        imageUrl: '',
        creator_handle: '@chessperiment',
        stars_total: 15,
        stars_count: 4,
        views: 180,
        forkCount: 0,
        isNew: false,
        date_published: new Date('2024-01-25'),
        rating: 3.8,
        reviewCount: 1,
    },
];
