const fs = require('fs');

// Read the German file
const deRaw = fs.readFileSync('./src/messages/de.json', 'utf8');
const de = JSON.parse(deRaw);

// Comprehensive translation map
const translations = {
    'Spielen': 'Play',
    'Spiel': 'Game',
    'Spiele': 'Games',
    'Spieler': 'Players',
    'Spielstatus': 'Game Status',
    'Spielstatistiken': 'Game Statistics',
    'Spielstatistik': 'Game Statistic',
    'Spielaktionen': 'Game Actions',
    'Spiel gestartet': 'Game Started',
    'Spiel beendet': 'Game Over',
    'Spiel beendete': 'Game Ended',
    'Raum': 'Room',
    'Räume': 'Rooms',
    'Raumcode': 'Room Code',
    'Raum erstellen': 'Create Room',
    'Raum beitreten': 'Join Room',
    'Raum verlassen': 'Leave Room',
    'Projekt': 'Project',
    'Projekte': 'Projects',
    'Meine Projekte': 'My Projects',
    'Neues Projekt': 'New Project',
    'Projektname': 'Project Name',
    'Brett': 'Board',
    'Bretter': 'Boards',
    'Board-Editor': 'Board Editor',
    'Brett-Editor': 'Board Editor',
    'Brett-Name': 'Board Name',
    'Brett bearbeiten': 'Edit Board',
    'Brett speichern': 'Save Board',
    'Brett erfolgreich gespeichert': 'Board saved successfully',
    'Brett zurücksetzen': 'Reset Board',
    'Figur': 'Piece',
    'Figuren': 'Pieces',
    'Figuren-Editor': 'Piece Editor',
    'Figuren-Studio': 'Piece Studio',
    'Figurenname': 'Piece Name',
    'Figuren im Set': 'Pieces in Set',
    'Figuren im Projekt': 'Pieces in Project',
    'Figur löschen': 'Delete Piece',
    'Figur speichern': 'Save Piece',
    'Figur erfolgreich gespeichert': 'Piece saved successfully',
    'Figur erfolgreich geladen': 'Piece loaded successfully',
    'Marktplatz': 'Marketplace',
    'Element': 'Item',
    'Elemente': 'Items',
    'Element erstellen': 'Create Item',
    'Element veröffentlichen': 'Publish Item',
    'Bibliothek': 'Library',
    'Set': 'Set',
    'Sets': 'Sets',
    'Neues Set': 'New Set',
    'Set-Name': 'Set Name',
    'Set wechseln': 'Switch Set',
    'Editor': 'Editor',
    'Über uns': 'About Us',
    'Feedback': 'Feedback',
    'Menü': 'Menu',
    'Anmelden': 'Log In',
    'Abmelden': 'Log Out',
    'Englisch': 'English',
    'Deutsch': 'German',
    'Sprache': 'Language',
    'Neuigkeiten': 'News',
    'Benachrichtigungen': 'Notifications',
    'Creator Dashboard': 'Creator Dashboard',
    'Beschreibung': 'Description',
    'Titel': 'Title',
    'Preis': 'Price',
    'Typ': 'Type',
    'Bild-URL': 'Image URL',
    'Bild-URL Hilfe': 'Image URL Help',
    'Bild hochladen': 'Upload Image',
    'Visuelle Basis': 'Visual Base',
    'Anleitung': 'Guide',
    'Klicken': 'Click',
    'Löschen': 'Delete',
    'Löschen bestätigen': 'Confirm Delete',
    'Zu Projekt kopieren': 'Fork to Editor',
    'Zum Editor kopieren': 'Copy to Editor',
    'In Projekt importieren': 'Import to Project',
    'In Bibliothek importieren': 'Import to Library',
    'Bibliothek importieren': 'Import to Library',
    'Bibliothek hinzufügen': 'Add to Library',
    'Zur Bibliothek hinzufügen': 'Add to Library',
    'Veröffentlichen': 'Publish',
    'Zurück': 'Back',
    'Zurück zum Projekt': 'Back to Project',
    'Zurück zu den Projekten': 'Back to Projects',
    'Zurück zum Marktplatz': 'Back to Marketplace',
    'Zurück zum Start': 'Back Home',
    'Zurück zum Menü': 'Back to Menu',
    'Zurück zur Lobby': 'Back to Lobby',
    'Zurück zu': 'Back to',
    'Fortfahren': 'Continue',
    'Abbrechen': 'Cancel',
    'Speichern': 'Save',
    'Kopieren': 'Copy',
    'Kopiert': 'Copied',
    'Teilen': 'Share',
    'Link teilen': 'Share Link',
    'Senden': 'Send',
    'Beitreten': 'Join',
    'Erstellen': 'Create',
    'Starten': 'Start',
    'Beenden': 'End',
    'Neu': 'New',
    'Neu eingetroffen': 'New Arrival',
    'Leeren': 'Clear',
    'Leinwand leeren': 'Clear Canvas',
    'Radiergummi': 'Eraser',
    'Rückgängig': 'Undo',
    'Wiederholen': 'Redo',
    'Laden': 'Loading',
    'Lade': 'Loading',
    'Suchen': 'Search',
    'Durchsuchen': 'Browse',
    'Keine Ergebnisse': 'No Results',
    'Nicht gefunden': 'Not Found',
    'Zugriff verweigert': 'Access Denied',
    'Fehler': 'Error',
    'Erfolgreich': 'Success',
    'Erfolg': 'Success',
    'Fehlgeschlagen': 'Failed',
    'Erforderlich': 'Required',
    'Profil': 'Profile',
    'Chat': 'Chat',
    'Nachricht': 'Message',
    'Nachricht senden': 'Send Message',
    'Zuschauer': 'Spectator',
    'Zug': 'Move',
    'Züge': 'Moves',
    'Gegner': 'Opponent',
    'Gegnerischer': 'Opponent\'s',
    'Du spielst': 'You Play',
    'Du bist dran': 'Your Turn',
    'Du bist am Zug': 'Your Turn',
    'Du hast gewonnen': 'You Won',
    'Du hast verloren': 'You Lost',
    'Gegner ist dran': 'Opponent\'s Turn',
    'Gegner hat': 'Opponent',
    'Gegner möchte': 'Opponent wants',
    'Gegner hat Remis angeboten': 'Opponent offered a draw',
    'Gegner hat die Verbindung getrennt': 'Opponent disconnected',
    'Weiß': 'White',
    'Schwarz': 'Black',
    'Farbe': 'Color',
    'Deine Farbe': 'Your Color',
    'Als Weiß spielen': 'Play as White',
    'Als Schwarz spielen': 'Play as Black',
    'Zufällige Farbe': 'Random Color',
    'Weiß am Zug': 'White\'s Turn',
    'Schwarz am Zug': 'Black\'s Turn',
    'Schach': 'Check',
    'Schachmatt': 'Checkmate',
    'Remis': 'Draw',
    'Unentschieden': 'Draw',
    'Remis anbieten': 'Offer Draw',
    'Remis annehmen': 'Accept Draw',
    'Remis ablehnen': 'Decline Draw',
    'Aufgeben': 'Resign',
    'Gegen Computer spielen': 'Play Against Computer',
    'Gegen Computer üben': 'Practice Against Computer',
    'Computerspiel': 'Computer Game',
    'Gegen Freund spielen': 'Play with Friend',
    'Gegen dich selbst spielen': 'Play Yourself',
    'VS dich selbst': 'VS Yourself',
    'Vs Stockfish KI': 'vs Stockfish AI',
    'gegen Stockfish KI': 'vs Stockfish AI',
    'Stockfish KI': 'Stockfish AI',
    'Stockfish': 'Stockfish',
    'KI': 'AI',
    'Schwierigkeit': 'Difficulty',
    'Elo auswählen': 'Select ELO',
    'Leicht': 'Easy',
    'Mittel': 'Medium',
    'Fortgeschritten': 'Intermediate',
    'Experte': 'Expert',
    'Meister': 'Master',
    'Großmeister': 'Grandmaster',
    'Anfänger': 'Beginner',
    'Hobbyspieler': 'Casual',
    'Verteidigungsspiel': 'Defensive Play',
    'Typ': 'Type',
    'Vorlagen': 'Presets',
    'Standard-Brett': 'Standard Board',
    'Leeres Brett': 'Empty Board',
    'Kleines Brett': 'Small Board',
    'Großes Brett': 'Large Board',
    'Gitter': 'Grid',
    'Gittergröße': 'Grid Size',
    'Gittertyp': 'Grid Type',
    'Quadrat': 'Square',
    'Hex': 'Hex',
    'Hexagonal': 'Hexagonal',
    'Symmetrie': 'Symmetry',
    'Zoom': 'Zoom',
    'Radius': 'Radius',
    'Reihen': 'Rows',
    'Spalten': 'Columns',
    'Feld': 'Field',
    'Felder': 'Fields',
    'Plätze': 'Squares',
    'Vorheriger Zug': 'Previous Move',
    'Nächster Zug': 'Next Move',
    'Aktueller Zug': 'Current Move',
    'Letzte Züge': 'Last Moves',
    'Zuletzt bearbeitet': 'Last Edited',
    'Bauer': 'Pawn',
    'Springer': 'Knight',
    'Läufer': 'Bishop',
    'Turm': 'Rook',
    'Dame': 'Queen',
    'König': 'King',
    'Platzieren': 'Place',
    'Platziere': 'Place',
    'Wähle': 'Choose',
    'Wählen': 'Select',
    'Sammlung': 'Collection',
    'Zusammenfassung': 'Summary',
    'Verwalte': 'Manage',
    'Verwalte und teile': 'Manage and share',
    'Statistik': 'Statistics',
    'Live': 'Live',
    'Bereit': 'Ready',
    'Warten': 'Waiting',
    'Warte auf': 'Waiting for',
    'Verbinde': 'Connecting',
    'Verbindung': 'Connection',
    'Verbindung getrennt': 'Disconnected',
    'Mit': 'With',
    'Gewinnen': 'Win',
    'Verlieren': 'Lose',
    'Alle': 'All',
    'Alle Elemente': 'All Items',
    'Kostenlos': 'Free',
    'Premium': 'Premium',
    'Designs': 'Designs',
    'Jetzt kaufen': 'Buy Now',
    'Kaufen': 'Buy',
    'Bedingungen': 'Terms',
    'Datenschutz': 'Privacy',
    'Imprint': 'Imprint',
    'Erste Schritte': 'Getting Started',
    'Thema': 'Theme',
    'Dunkelheit': 'Dark',
    'Helligkeit': 'Light',
    'Startseite': 'Home',
    'Spiel starten': 'Start Playing',
    'Eigenes Spiel erstellen': 'Create Your Game',
    'Analysiere': 'Analyze',
    'Angesagt': 'Trending',
    'Schnellerstellen': 'Quick Create',
    'Projekte aktiv': 'Active Projects',
    'Unbenanntes Projekt': 'Unnamed Project',
    'Erstelle dein erstes Projekt': 'Create Your First Project',
    'Noch keine Projekte': 'No Projects Yet',
    'Keine Bewertungen': 'No Reviews',
    'Stelle sicher': 'Make sure',
    'Letzten': 'Latest',
    'Gestalte deine': 'Design Your',
    'Schlachtfelder': 'Battlefields',
    'Erstelle': 'Create',
    'individuelle': 'Custom',
    'Schachkonfigurationen': 'Chess Configurations',
    'Ziehe': 'Drag',
    'klicke': 'Click',
    'Umschalten': 'Toggle',
    'Vergrößern': 'Resize',
    'Rändern': 'Edges',
    'Schachfigur-Vektoren': 'Chess Vector Pieces',
    'von': 'by',
    'Vecteezy': 'Vecteezy',
    'Entwirf deine': 'Design Your',
    'Schachfiguren': 'Chess Pieces',
    'pixelgenaue': 'Pixel-Perfect',
    'intuitiven': 'Intuitive',
    'Invertieren': 'Invert',
    'Farben': 'Colors',
    'überschreibt': 'overwrites',
    'Invertieren der Farben': 'Invert Colors',
    'aktuelle Design': 'Current Design',
    'Pixelierung': 'Pixelation',
    'verringert': 'Reduces',
    'Qualität': 'Quality',
    'Deine Sammlung': 'Your Collection',
    'Hinzufügen': 'Add',
    'Gegenfarbe generieren': 'Generate Opposite Color',
    'erfolgreich gespeichert': 'saved successfully',
    'erfolgreich geladen': 'loaded successfully',
    'Fehler beim Speichern': 'Error saving',
    'Fehler beim Laden': 'Error loading',
    'Creator Studio': 'Creator Studio',
    'Befindet sich aktuell': 'Currently in',
    'Beta-Phase': 'Beta',
    'ausgewählte Ersteller': 'Selected Creators',
    'verfügbar': 'Available',
    'Visuelle Zuglogik': 'Visual Move Logic',
    'Definiere': 'Define',
    'Blöcke zusammenziehst': 'Blocks together',
    'Bewegungsmuster': 'Movement Pattern',
    'Bewegungsmuster hinzufügen': 'Add Movement Pattern',
    'Regel': 'Rule',
    'Wenn': 'If',
    'UND': 'AND',
    'Erlaubt': 'Legal',
    'Verboten': 'Illegal',
    'Noch keine Bewegungsmuster': 'No movement patterns yet',
    'Deine erste Regel': 'Your first rule',
    'Sammlung wählen': 'Select Collection',
    'Aktives Set': 'Active Set',
    'Kein Set ausgewählt': 'No Set Selected',
    'Neu hinzufügen': 'Add New',
    'Noch keine Figuren': 'No Pieces Yet',
    'Nochmal klicken': 'Click again',
    'Zum Bestätigen': 'to Confirm',
    'Verstanden': 'Got It',
    'Erweiterte Logik': 'Advanced Logic',
    'Öffne': 'Open',
    'knotenbasierten': 'Node-based',
    'Logik-Editor': 'Logic Editor',
    'Scratch-ähnlich': 'Scratch-like',
    'Demnächst': 'Coming Soon',
    'Verfügbar Ende Januar 2026': 'Available end of January 2026',
    'Wähle ein Set': 'Select a Set',
    'Neues Set erstellen': 'Create New Set',
    'Vorhandenes Set wählen': 'Choose Existing Set',
    'durchsuchen': 'Search',
    'werden geladen': 'Loading',
    'Fehler beim Erstellen': 'Error creating',
    'Horizontaler Schritt': 'Horizontal Step',
    'Anzahl der Felder': 'Number of squares',
    'horizontal zieht': 'moves horizontally',
    'Positiv ist rechts': 'Positive is right',
    'negativ ist links': 'negative is left',
    'Vertikaler Schritt': 'Vertical Step',
    'vertikal zieht': 'moves vertically',
    'Positiv ist vorwärts': 'Positive is forward',
    'negativ ist rückwärts': 'negative is backward',
    'Horizontaler Abstand': 'Horizontal Distance',
    'absoluten': 'Absolute',
    'unabhängig': 'Regardless of',
    'Vertikaler Abstand': 'Vertical Distance',
    'vorwärts oder rückwärts': 'Forward or backward',
    'Chessperiment Multiplayer': 'Chessperiment Multiplayer',
    'Tritt gegen': 'Play against',
    'Freunde': 'Friends',
    'spannenden Schachpartien': 'Exciting chess games',
    'nicht verfügbar': 'Not Available',
    'Nicht verfügbar': 'Not Available',
    'Mehr erfahren': 'Learn More',
    'Suche nach': 'Search for',
    'Lade tolle Elemente': 'Loading great items',
    'Suche nach Brettern': 'Search for boards',
    'Keine passenden Elemente': 'No matching items',
    'Bitte melde dich an': 'Please log in',
    'um Marktplatz-Elemente': 'to create marketplace items',
    'zu erstellen': 'to create',
    'Marktplatz befindet sich': 'Marketplace is currently',
    'Beta': 'Beta',
    'tolle Inhalte': 'great content',
    'bereitzustellen': 'provide',
    'Lokal spielen': 'Play Local',
    'Meistgesehen': 'Most Viewed',
    'Bestbewertet': 'Top Rated',
    'Meiste Bewertungen': 'Most Reviewed',
    'Neueste': 'Newest',
    'Im Marktplatz veröffentlichen': 'Publish to Marketplace',
    'Teile dein': 'Share Your',
    'mit der Community': 'with the Community',
    'Ein Titel ist erforderlich': 'Title is required',
    'Creator-Profil erforderlich': 'Creator Profile Required',
    'Du musst ein Creator-Profil': 'You must set up a creator profile',
    'einrichten': 'Set up',
    'bevor du veröffentlichen kannst': 'Before you can publish',
    'Figurensatz': 'Piece Set',
    'Bewertungen': 'Reviews',
    'Bewertung schreiben': 'Write Review',
    'Bewertung absenden': 'Submit Review',
    'Teile deine Erfahrung': 'Share Your Experience',
    'dieser Kreation': 'with this creation',
    'Deine Bewertung': 'Your Rating',
    'Melde dich an': 'Log in',
    'Bewertung konnte nicht': 'Review could not be',
    'abgesendet werden': 'submitted',
    'Diese Bewertung löschen': 'Delete this review',
    'Basierend auf einer Kreation von': 'Based on a creation by',
    'Spiel erstellen': 'Create Game',
    'Analyse': 'Analysis',
    'kommt bald': 'Coming Soon',
    'Mach dich bereit': 'Get ready',
    'nächste Level': 'next level',
    'kommendes Analyse-Tool': 'upcoming analysis tool',
    'leistungsstarke': 'Powerful',
    'Schach-Engine': 'Chess Engine',
    'vergangenen Spiele': 'past games',
    'tiefe Einblicke': 'Deep insights',
    'Strategie': 'strategy',
    'Entdecke deine Fehler': 'Discover your mistakes',
    'verpasste Chancen': 'missed opportunities',
    'brillanten Züge': 'brilliant moves',
    'schneller zu lernen': 'learn faster',
    'klüger zu spielen': 'play smarter',
    'Alle': 'All',
    'Alle Spiele': 'All Games',
    'Keine Bewertungen': 'No Reviews',
    'Sei der Erste': 'Be the first',
    'Bereits bewertet': 'Already reviewed',
    'Basierend auf': 'Based on',
    'History Mode': 'History Mode',
    'Raum ist bereits voll': 'Room is full',
    'Du bist bereits': 'You are already',
    'Suche nach Spiel': 'Searching for game',
    'würdigen Gegner': 'Worthy opponent',
    'Privaten Raum erstellen': 'Create Private Room',
    'Erzeuge einen Code': 'Generate a code',
    'Freunde einzuladen': 'to invite friends',
    'Schnelles Spiel': 'Quick Play',
    'Privaten Raum erstellen': 'Create Private Room',
    'Findingmatch': 'Finding match',
    'würdigen Gegner': 'Worthy opponent',
    'Suche abbrechen': 'Cancel search',
    'Stockfish KI': 'Stockfish AI',
    'Im Spiel': 'In game',
    'Spiel beendet': 'Game over',
    'Du hast gewonnen': 'You won',
    'Du hast verloren': 'You lost',
    'Nochmal spielen': 'Play again',
    'Zurück zum Menü': 'Back to menu',
    'Zuschauer': 'Spectating',
    'Geschlagen': 'Captured',
    'Zeit': 'Time',
    'Unbegrenzt': 'Unlimited',
    'Stil wählen': 'Select Style',
    'Stil suchen': 'Search Style',
    'Kein Stil gefunden': 'No Style found',
    'Zurücksetzen': 'Reset',
    'Menü': 'Menu',
    'Design': 'Design',
    'Möchtest du das Spiel wirklich verlassen': 'Do you really want to leave the game',
    'Verlassen': 'Leave',
    'Warten': 'Waiting',
    'Du': 'You',
    'Weiß am Zug': 'White\'s turn',
    'Schwarz am Zug': 'Black\'s turn',
    'Aktueller Zug': 'Current move',
    'Zurück zur Lobby': 'Back to lobby',
    'Match-Details': 'Match Details',
    'Kein aktiver Raum': 'No active room',
    'Kopieren': 'Copy',
    'Kopiert': 'Copied',
    'Nachricht eingeben': 'Type message',
    'Tritt meinem Chessperiment-Spiel bei': 'Join my Chessperiment game',
    'Tritt meinem Schachspiel bei': 'Join my chess game',
    'Verbinden': 'Connecting',
    'Schnelle Suche': 'Quick search',
    'Revanche': 'Rematch',
    'Neues Spiel': 'New Game',
    'Gegner möchte eine Revanche': 'Opponent wants rematch',
    'Revanche angefragt': 'Rematch requested',
    'Remis akzeptiert': 'Draw accepted',
    'Remis-Angebot abgelehnt': 'Draw offer declined',
    'Du hast das Remis-Angebot abgelehnt': 'You declined the draw offer',
    'Remis-Angebot erhalten': 'Draw offer received',
    'Info': 'Info',
    'Züge': 'Moves',
    'Chat': 'Chat',
    'LIVE': 'LIVE',
    'Schreib etwas': 'Write something',
    'Spielstatus': 'Game Status',
    'Spielstatistiken': 'Game Statistics',
    'Spielstatistik': 'Game Statistic',
    'Raumcode': 'Room Code',
    'Spieler': 'Players',
    'Du spielst': 'You Play',
    'Deine Seite': 'Your Side',
    'Verbinde': 'Connecting',
    'Titel': 'Analysis feature coming soon',
    'Mach dich bereit': 'Get ready',
    'nächste Level': 'next level',
    'kommendes Analyse-Tool': 'upcoming analysis tool',
    'leistungsstarke Schach-Engine': 'powerful chess engine',
    'vergangenen Spiele': 'past games',
    'tiefe Einblicke': 'deep insights',
    'Strategie': 'strategy',
    'Entdecke deine Fehler': 'Discover your mistakes',
    'verpasste Chancen': 'missed opportunities',
    'brillanten Züge': 'brilliant moves',
    'schneller zu lernen': 'learn faster',
    'klüger zu spielen': 'play smarter',
    'Schachfigur-Vektoren von Vecteezy': 'Chess vector pieces from Vecteezy',
};

// Function to translate text
function translateDE2EN(text) {
    if (typeof text !== 'string') return text;
    if (translations[text]) return translations[text];
    return text;
}

// Recursive function to translate object
function translateObject(obj) {
    if (typeof obj === 'string') {
        return translateDE2EN(obj);
    } else if (Array.isArray(obj)) {
        return obj.map(translateObject);
    } else if (typeof obj === 'object' && obj !== null) {
        const result = {};
        for (const key in obj) {
            result[key] = translateObject(obj[key]);
        }
        return result;
    }
    return obj;
}

// Translate the entire object
const en = translateObject(de);

// Write to file
fs.writeFileSync('./src/messages/en.json', JSON.stringify(en, null, 4));

console.log('English translation created successfully!');
